### ISSUE TITLE
CUDA 9 support?

### ISSUE THREAD

**Issue by blueberry** [jcuda/jcuda#12]
@gpu

Hi Marco,

Since CUDA 9 has been released, do you have any (approximate and non-binding, of course) schedule for supporting it in JCuda and related libraries?

Thanks for creating JCuda in the first place :)

**Comment by archenroot** [comment]
@blueberry during my time with Java, GPU and AI stuff development I started with JCuda, but later focused only on JavaCPP bridge which in this specific case has support for what you are asking:
https://github.com/bytedeco/javacpp-presets/commit/8b3c6057a265b0ab9534a04299ee0ba4c0d0c6c9

Actually more important is that I suggest to merge/make obsolete this project in favor of JavaCPP and propose to developers of this project and jopencl as well to focus on JavaCPP stuff as it has much wider focus.

NOTE: We started discussion already about developing AI framework which will be capable to convert any kind of C++ and bring it into Java world. I know it might sound in the moment challenging and it is (and neither of us have time now), but that is the one of possible futures of JavaCPP project.

**Comment by blueberry** [comment]
I know about javacpp, but I have had fantastic experience with JCuda and JOCL. I also tend to agree with @jcuda  technical decisions and his attention to detail, so I really want to use his libraries as long as he wishes to maintain them.

It is perhaps an advantage of javacpp that it provides the FFI to so many libraries, but I currently do not need those. I prefer to use JCuda/JOCL to create my own implementations of those AI/ML algorithms that I need. JCuda/JOCL and related Marco's libraries enable me to do exactly that, with carefully crafted interface and technical decisions that I can agree with. Moreover, you could see that Marco's libraries are created with lots of affection, while javacpp is a large collection of machine generated interfaces to libraries that I am not sure the authors employed by Skymind personally know in such detail or sometimes even use at all. In other words, I prefer quality over quantity.

As for merging, I'd leave that discussion to @jcuda

**Comment by archenroot** [comment]
@blueberry @jcuda I see and understand of course, that is just actually possible article for discussion. 

JavaCPP is actually not only based on machine crafted interfaces, but requires (in the moment) knowledge of adopted library in very detail. This exactly the reason we started discussion about AI powered auto converter network to automate this completely. In the moment it depends on the user to provide "mapping". Let's see, instead of 2 I would personally rather see 1 project which inherits pros from both -> quality.

Still the versions you are asking for are already available in JavaCPP.

**Comment by jcuda** [comment]
Regarding the original issue: I had seen the announcement of the CUDA 9.0 developer preview, but not yet started the update. Now that they released the final CUDA 9.0 version, the update will directly be based on that. Regarding the timeline: There are currently some other issues being discussed, considering some low-level (but important) details regarding the memory handling. It should be possible to do some of the work here in parallel, because it should be independent of the API changes, but I'll have to take a closer look at the *actual* API changes for CUDA 9.0 first.

About merging with JavaCPP or abandoning JCuda: This could be a rather broad topic, and I don't think that this GitHub issue is the appropriate place to discuss it. I have opened a thread about this at https://forum.byte-welt.net/t/about-jcuda-and-javacpp/19538 (but if you don't want to register there, feel free to add comments here as well)

**Comment by jcuda** [comment]
Support for CUDA 9.0.176 has been added with https://github.com/jcuda/jcuda/commit/9bfa010e1cb445a5bffecc1acf41bb4c3b20ff74 

There may still be changes to be done regarding the current handling of arrays, particularly regarding async operations. This has been discussed in https://forum.byte-welt.net/t/multiple-threads-getprimitivearraycritical/19535 and partially addressed in the branch https://github.com/jcuda/jcuda/tree/no_critical

I have not decided yet whether there will be a "0.9.0" release with the current state and a "0.9.0a" release with the fixes, or whether the fixes will already be added to the 0.9.0 release directly.

In any case, leaving this issue open until the Maven release is done.

**Comment by hadim** [comment]
Is that possible to test the CUDA 9 support with Maven?

**Comment by jcuda** [comment]
JCuda 0.9.0 has not been uploaded to Maven Central yet. I'd really like to add some more tests covering the new features. And I hoped that some people might try it out and provide some feedback (but since I added some missing files only 2 days ago, obviously (and unfortunately), nobody had tried it so far...)

I'll try to at least create the "pre-release" tag next week. Then I still have to rely on contributors to provide the Mac (and preferably Linux) binaries. So the Maven release may still take a few days. If it is helpful for you, I could provide a (Windows) SNAPSHOT release for you to test it locally earlier.

**Comment by hadim** [comment]
I am having a hard time installing Cuda 8.0/8.1 on my computer and so I am stuck with 9.0 on Windows (no problem on Linux to run JCuda with Cuda 8.0).

Let me know when you have those pre-release ready. I can test it on Windows and Linux.

**Comment by jcuda** [comment]
There are no specific changes planned before the pre-release tag is created. I'd just do a clean checkout+build of the current state locally, and if everything runs smoothly, I'd create the tag. So you can already give it a try, and **if** you encounter any issues, just drop me a note. Otherwise, I'll try to do this dry run this week (but still have some other tasks in the queue, so I cannot give a specific date)

**Comment by hadim** [comment]
I'll wait for you to release the artifacts Thanks!

**Comment by jcuda** [comment]
The tag has been created, and the further process of the Maven Central release of 0.9.0 is tracked at https://github.com/jcuda/jcuda-main/issues/21 (so I'll close this one for now)
