### ISSUE TITLE
Thread safety of nio ByteBuffer

### ISSUE THREAD

**Issue by PavelSosin-320** [jcuda/jcuda#25]
JCuda Pointer class uses nio ByteBuffer to wrap java arrays. Unfortunately nio ByteBuffer is neither thread safe nor shields memory from Garbage collector. This utility class belongs to nio package and is usable only in IO context. The correct solution how to allocate pined memory in Java outside the heap is discussed in [Memory allocation outside the heap](https://stackoverflow.com/questions/35241715/allocating-memory-outside-jvm-and-using-it-inside-jvm).  I afraid that only correct solution involves JNI. In this case allocated memory can be both thread safe and not managed by GC. Memory allocated in such way can be filled by java code and transfered to CUDA like in C programs. If accessed via synchronized methods it is thread safe too. Unfortunately I'm very rusted C programmer and can't take this topic for implementation.

**Comment by jcuda** [comment]
An own resource manager can be tricky. How to know whether a buffer is "unreferenced"? You cannot rely on `finalize()`, and also not on `SoftReference` or `WeakReference`, for that matter. This is especially true for resources that are not managed by the JVM, like GPU memory or host memory that was allocated outside of the JVM. 

There certainly is a clash of worlds when Java and the GPU come together, and one should carefully consider whether the headaches that may be caused by the mix of Java Threads, GC, the (necessarily manual!) memory management with `cudaMalloc` and `cudaFree` calls and possibly asynchronous operations in CUDA are justified when trying to build any sort of "high-level abstraction layer" on top of something like CUDA. CUDA has **strict** constraints regarding the question which resource may be used by which host thread at which point in time, and one has to **carefully** read the specs in order to make sure that each resource that you are using belongs to the context that is "current" for the host thread. 

(If you know more about this: Consider writing an answer to my question at https://stackoverflow.com/q/48676001/3182664 - I'd really like to get that "handle" concept into https://github.com/jcuda/jcuda-vec at some point...)

However, I don't know the details of your system, but regarding the thread usage and buffers: When this is *only* about buffers and their use from multiple **Java**-threads, maybe https://docs.oracle.com/javase/8/docs/api/java/lang/ThreadLocal.html could offer some options here...?



https://docs.oracle.com/javase/8/docs/api/java/lang/ThreadLocal.html

**Comment by PavelSosin-320** [comment]
Of course, I'm against putting all code inside huge synchronized block. Global Try {} catch {} is also required to avoid memory leaks. So, what is the scope of syncronized block? It looks like total mess. The problem for me is the design of Pointer class based on nio Buffers. Neither allocate nor allocate direct are not directly allocate memory out of the heap. The dufference is only that ByteBuffer is marked for direct IO.
All nio Buffers are backed by Java NIO native code and native IO buffers. Memory allocated by CUDA calls is out-of-the heap pined memory. Buffers are simple native code wrapper classes which wrap physical IO memory with Buffer Interface. They are managed by Java nio and GC and have own Lock().  It is not a problem to make Pointer thread safe but it will not help to make CUDA Memory thread safe. Fine grained Lock and unlock can be done only outside. It is very easy to ensure memory release using Java 9 Cleaner too. But pointer can be registered in Cleaner only outside too because it's prohibited to run Cleaner's actions in the same Class or its inner classes.
Writing paralell Java code already several years I prefer to never create Threads directly but use Thread pool and Executor service which optimizes Hardware resource usage for me. All my Classes running application code extend Executor. It is true regarding my colleages. 
Say, I want to execute sequence of Cuda libraries operations accepting several parameters and  need to allocate several buffers. The logic of emory management is going to be more and more complex. I suppose that the correct pattern is Observer which allocates and locks memory on applicarion code fired events.
Direct instantiation of Pointer using is also inconvinient - Class.forName and JNI call <init> newObject are nightmare for overloaded constructors. The better solution is simple constructor with single parameter Type and factory method which does pointer = new Pointer(), pointer.allocates memory and registers pointers for cleaning. The same class which provides this factory method will server as Observer/Litener to lock and unlock memory on application code events including thread exit by exception.
And finally, why I need Pointer in Java at all in absence of pointer arithmetics (&,*,->) if I use Buffer interface? Java long can't store C pointer because this assumption  is not supported by any specification and almost certainly wrong for ARM. Actualy, there is no way in Java to store void pointer according Java specification. It is possible only inside native code structure.

**Comment by PavelSosin-320** [comment]
But 5 minutes solution exists too:
Use ExecutorService.newSingleThreadExecutor to access not thread safe resources and put all your stuff into Runnable or Callable class. I like callable which returns CompletableFuture because it allows to split long execution chain into short running time  (prepare- exec - process) steps.

**Comment by jcuda** [comment]
There are many (seemingly random) thoughts and keywords mixed into that comment. 

An attempt of a response, starting at a high level, and going into a few, selected details: 

Much of the synchronization issues for CUDA as well as for JCuda are left to the developer. The *user* of the API has to make sure that everything is accessed from the right thread. You simply cannot expect that JCuda introduces a level of synchronization and thread safety that *does not exist in CUDA*. JCuda is supposed to be a 1:1 mapping of the CUDA functions, and this is intentional: I offer the JNI layer. What others are building on top of that is up to them.

Or more specifically: Where **exactly** do you see a synchronization issue or a resource management issue that exists in JCuda, but **not** in CUDA?

---

> Neither allocate nor allocate direct are not directly allocate memory out of the heap. The dufference is only that ByteBuffer is marked for direct IO.
> All nio Buffers are backed by Java NIO native code and native IO buffers. Memory allocated by CUDA calls is out-of-the heap pined memory. Buffers are simple native code wrapper classes which wrap physical IO memory with Buffer Interface. They are managed by Java nio and GC and have own Lock(). 

There is a difference between direct and non-direct buffers (and there are dozens of implementations of `ByteBuffer`, for different use cases, even though much of their (common) functionality is, at some point, based on JVM intrinsics). For direct buffers, the documentation says

>  The contents of direct buffers may reside outside of the normal garbage-collected heap,
> An implementation of the Java platform may optionally support the creation of direct byte buffers from native code via JNI.

Basically **every** JNI library that I am aware of **only** uses direct buffers. However, for JCuda, I had the goal of also supporting non-direct buffers (which are essentially wrappers around Java arrays). The reason is that one core usage pattern of CUDA/JCuda is simple:

- Upload **lots** of data to the GPU
- Call some kernel on the data
- Copy some result data back to the host

In most applications that CUDA is "good for", the input data on Java side already resides in large `float[]` arrays. Copying the data to the GPU already *is* a bottleneck. And I really wanted to avoid the *additional* overhead of first copying the `float[]` array into a direct `FloatBuffer`, and then copy this to the GPU. This caused some headaches, difficulties, and maybe even limitations, but I think it is important for the majority of use-cases.

---

The reverse direction is when you allocate (host!) memory with CUDA, and want to make this accessible for Java. For this, there is the [`newDirectByteBuffer`](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html#NewDirectByteBuffer) function. The returned buffer is totally out of the control of the JVM. The caller has to deallocate the memory at some point. And the caller is responsible for *not* accessing the byte buffer after the memory was deallocated.

---

> It is very easy to ensure memory release using Java 9 Cleaner too. 

I have seen, but not actively used the `Cleaner` class. But similar to approaches of memory management that are based on things like a `SoftReference`: **You cannot let the JVM control the management of GPU memory**. This is simply not the responsibility of the JVM, and not feasible on a technical level for various reasons. Dealing with the GC is already hard enough...

---

> All my Classes running application code extend Executor. It is true regarding my colleages.

That sounds awful. 

---

> Say, I want to execute sequence of Cuda libraries operations accepting several parameters and need to allocate several buffers. The logic of emory management is going to be more and more complex. I suppose that the correct pattern is Observer which allocates and locks memory on applicarion code fired events.
> Direct instantiation of Pointer using is also inconvinient - Class.forName and JNI call newObject are nightmare for overloaded constructors. The better solution is simple constructor with single parameter Type and factory method which does pointer = new Pointer(), pointer.allocates memory and registers pointers for cleaning. The same class which provides this factory method will server as Observer/Litener to lock and unlock memory on application code events including thread exit by exception.

I'm not entirely sure what you want to suggest here, but again:

- Creating a Pointer cannot allocate the memory
- "Cleaning" the allocated memory of a Pointer cannot be done by the JVM

I know that it would be desirable to have a "thicker abstraction layer". A nice, object-oriented, idiomatic (!) Java API for GPU computations would be great. But I did never seriously attempt that. And if you wonder why I never attempted this, I have to make the snarky comment: Try it. You'll come into a hell of synchronization and memory management issues, and into the dilemma:

1. the API only supports the most trivial use-cases. In this case, nobody will use it. Everybody can write a few utility methods for his own use-case
2. The API is really convenient and powerful. In this case, nobody will use it. The complexity that is *inherent* when using something like CUDA can then only be offered "in a different flavor", but still leaving the responsibility for synchronization and management to the user .

---

> And finally, why I need Pointer in Java at all in absence of pointer arithmetics (&,*,->) if I use Buffer interface? Java long can't store C pointer because this assumption is not supported by any specification and almost certainly wrong for ARM. Actualy, there is no way in Java to store void pointer according Java specification. It is possible only inside native code structure.

The `Pointer` is an attempt of an abstraction of arbitrary memory in Java. It should work for Java arrays, (direct) buffers, and GPU memory. I (naively) created it 10 years ago. I know that it is far from perfect, and if I had to re-design it from scratch, I'd certainly do it differently. By the way: The `Pointer` class *does* offer some form of pointer arithmetic, via [`Pointer#withByteOffset`](http://www.jcuda.org/jcuda/doc/jcuda/Pointer.html#withByteOffset(long)). However, it's not designed to support "dereferencing" or "taking the address of something" like in C, because C and Java are different programming languages. 

However, I'm not up to argue about whether it is sensible, or whether storing the address in a `long` is appropriate. Have a look at 

- the [`Pointer` class in JNA](https://github.com/java-native-access/jna/blob/master/src/com/sun/jna/Pointer.java#L68)
- the [`Pointer` class in BridJ](https://github.com/nativelibs4java/BridJ/blob/373c03447df44b5a5508e94fa897369b41b18f48/src/main/velocity/org/bridj/Pointer.java#L353)
- the [`Pointer` class in JavaCPP](https://github.com/bytedeco/javacpp/blob/master/src/main/java/org/bytedeco/javacpp/Pointer.java#L531)
- any other emulation of a "pointer" that you can find in Java...

and finally: 

- the [`ScopeImpl`](http://hg.openjdk.java.net/panama/dev/file/7b4fde6e874b/src/java.base/share/classes/jdk/internal/foreign/ScopeImpl.java#l230) which serves as the basis for allocating memory for a `Pointer` in Project panama.

The last one is an interesting pointer (pun intended), by the way: Project Panama aims at providing an infrastructure for accessing native libraries like CUDA from Java. I made an experiment for that a while ago:  https://mail.openjdk.java.net/pipermail/panama-dev/2019-February/004443.html . In fact, I'm (somehow) in contact with the developers, talking about the options related to Panama, CUDA and JCuda. If you think that JCuda does not suit your needs, you could consider building your own CUDA bindings, with one of the early access builds of Panama, available at https://jdk.java.net/panama/

**Comment by PavelSosin-320** [comment]
I have some experiance with application developers as end users and have no hope that application developer is able to read more than 20 lines of documetation. He / she is speialist in application mataematics or physics, maybe CUDA enabled algorithms but not in resource locking. It is up to framework developer to provide template solutions, detect the places where application developer will certainly make mistakes and provide instructions how to avoid them. The best way is to provide Abstract/Base class which implements all critical sections without flaws. It is not interesting why native code or NVidia toolkit library or NIO Buffers are not thread safe - Jcuda has to provide either solution or workaround via Java locking to JCuda user. This is the purpose of my **Integration test**. If the root cause is in underlying layer - report to its developers today!

**Comment by jcuda** [comment]
Sure, I understand the desire and importance of having an abstraction layer. Things like Python suggest that this is possible, but that's debatable. 

It would be nice to have code like

    float result[] = withThreads(10).withGpus(GPUS.ALL).uploadData(input).execute(kernel).readResult();

And of course, it's possible to do that. But the details of the host-thread dependent CUDA context management, possibly multiple GPUs, GC, and the fact that resource management cannot be done by the JVM, this can only sensibly be implemented for *very* simple application cases. And then, people say: "Hey, I have 2D data", and/or "I want to be notified via a callback when a certain execution step finished", and then you'll have to think about how much of the nitty, gritty details you are willing to expose to the users...

And again: The goal of JCuda was never to provide an abstraction layer. The goal was rather: *Everything* that is possible with CUDA should be possible with JCuda. (Which includes "messing up your system due to wrong synchronization"). Of course, **not** everything is possible - the limitations are listed on the website. 

But in any case: If you find further limitations or things that could be improved, just let me know.

**Comment by jcuda** [comment]
If there are any issues coming out of your test, you can open them as separate issues here.
