### ISSUE TITLE
on JDK17,  performance slowdown significantly after a few days

### ISSUE THREAD

**Issue by thekiki** [jcuda/jcuda#37]
setup env: linux, jcuda10.2, cuda11.4, JDK17

The typical process routine of our serivce includes:
1. host to device copy
2. lauch kernel
3. device to host copy
4. cuStreamAddCallback
5. trigger host function to deal with results already copied into host buffer

all happens in streams concurrently.

We run this service with JDK8 without any issue, but when trying JDK17, things goes quite weird. After one or two days since service restarted, the performance becomes very slow, maybe 10x slower.

We have tried do some profiling, and find this stack eats up quite a lot CPU cycles:
cuStreamAddCallback_NativeCallback(CUstream_st*, cudaError_enum, void*)-->jni_DetachCurrentThread-->ObjectSynchronizer::release_monitors_owned_by_thread

Asking help for this performance issue, Thanks

**Comment by jcuda** [comment]
The stream callbacks are a bit subtle, and it _might_ be that there is some cleanup operation missing [near this part of the code](https://github.com/jcuda/jcuda/blob/a8663fc9287ad1506aedc865e7195ef2b832dc85/JCudaDriverJNI/src/JCudaDriver.cpp#L680).

You _specifically_ said that this happens only on JDK17, and I haven't that one installed, so would have to allocate some time to do this. Then I'd modify the [callback sample](https://github.com/jcuda/jcuda-samples/blob/master/JCudaSamples/src/main/java/jcuda/driver/samples/JCudaDriverBasicStreamCallback.java) to just execute the `cuStreamAddCallback` as part of a loop, and see what happens. If it becomes slow (although I won't run it for several days, that's for sure), I'd have to read more about whether there are any changes in the JNI layer that might cause this behavior - but my gut feeling is that this will involve some experiments and guesses...

**Comment by thekiki** [comment]
Thanks for your time and looking forward your experiments

some follow up for this issue, We've confirmed that this performance downgrade would not happen when switch to sync style API instead of callback

**Comment by jcuda** [comment]
Don't hold your breath, though: It's hard to make promises about a _timeline_ here, and even less about _results_. 

I could go on, weaseling around the issue...

- Have you tried switching it off and on again? (And it sounds like this could be a case where this may not even be a "snarky comment", but might be a legitimate question...)
- Can't you just use JDK8?
- Can't you just use the synchronous API? 
- Feel free to analyze the reason of the problem, and suggest a solution
- Feel free to open a PR...
- In doubt, there are alternatives - maybe it works with https://github.com/bytedeco/javacpp-presets/tree/master/cuda ? 

JCuda is a one-man, spare-time project. I've sunk hundreds (probably thousands) of hours into that. I cannot spend extensive amounts of time and provide support for hyper-specific, subtle, hard-to-analyze issues like this. I can only _try_ to allocate some time, and _try_ to see whether I can at least figure out what's wrong here, and _try_ to find possible solutions in reasonable time. I see this as one form of "maintenance", and as a form of "responsibility", but I can only _try_ to do all this, because there are trade-offs with other tasks...

**Comment by jcuda** [comment]
No further actions here, I guess...
