### ISSUE TITLE
Add support for stream callbacks

### ISSUE THREAD

**Issue by jcuda** [jcuda/jcuda#9]
The stream callbacks (see [CUDA documentation](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#stream-callbacks)) are one of the main functionalities that are not yet supported in JCuda. Calling a function to set up a stream callback will cause an `UnsupportedOperationException`. 

Although there seemed to be not much demand for this functionality in the past, it is a possibly important feature for certain forms of synchronization. The fact that it was introduced in CUDA 5.0 in 2012 and is still not supported by JCuda is embarassing. 

The goal of this issue is to trigger the process of actually implementing them, track the progress and discuss possible related issues.

**Comment by jcuda** [comment]
Support for stream callbacks was added in https://github.com/jcuda/jcuda/commit/c49969d419633d089ee4f9766f8d8b26105679e3 

Samples showing the basic usage of stream callbacks have been added in https://github.com/jcuda/jcuda-samples/commit/dc645d5b267b489507cb5b94fb9ecd63b17d682a

**Comment by blueberry** [comment]
@jcuda 

Hi Marco,

I've just stumbled to this issue. I'm using JCuda 0.8.0 from the maven repository, and calling cuStreamAddCallback throws UnsupportedOperationExceptiion. I've not tried your example code exactly, since I use ClojureCUDA, but I checked my Clojure example, and it follows what you do in the Java JCuda example.

What could be the issue here? Did the code that was used for 0.8.0 include this fix?

**Comment by jcuda** [comment]
No, the support for stream callbacks was added *after* the 0.8.0 release. 

There was not much demand for this feature (that's also why it was added so late...), so I did not (yet) create a new release for it. I could create a "0.8.0**b**" release with stream callback support, but ... I think that CUDA 8.5 or CUDA 9.0 will be announced soon, so this feature will likely be part of the next JCuda version.

(BTW: I'll definitely have to think about a way to better support cases like this. Right now, re-compiling the library with the latest source code would allow you to use stream callbacks. But the *version number* will still be "0.8.0", so you'd have to manually update the native library...)

**Comment by blueberry** [comment]
@jcuda 

OK, I'm in no hurry yet. I just wanted to confirm whether I have a bug in my code. I'm perfectly fine with waiting for the next release of JCuda (I hope it is on a "a few months" rather than "next year" horizon). Regarding versions, maybe it would make sense to go with 0.8.1 or 0.8.0.1 for bugfix releases? I think there is not much space for confusion with CUDA versions, since CUDA itself have many minor version releases (like 8.0.xxx) and what is important is the major version (8, 9...) and maybe an ocasional 0.5...

**Comment by jcuda** [comment]
There have been "rumours" and "indications" for CUDA 8.5 since last year (IIRC, some drivers already said that they support 8.5, although there was no official announcement yet). If it turns out to take too long (or there are other important extensions or bugfixes), I'd create a new release.

Regarding the version number: You remember the discussion about JOCL and JOCLBlast. Somewhere around CUDA 2.x, I decided to use the version numbers of CUDA, but with a "0." prefix. I'll probably do the same here as for JOCL: The version numbers should match. For CUDA 8.5, I might create JCuda 8.5.0 (so that the last digit can be used for patches and bugfixes - in line with SemVer).
